---
- name: "Encryption | remove the unsafe ECDSA public key"
  ansible.builtin.file:
    path: /etc/ssh/ssh_host_ecdsa_key.pub
    state: absent

- name: "Encryption | remove the unsafe ECDSA private key"
  ansible.builtin.file:
    path: /etc/ssh/ssh_host_ecdsa_key
    state: absent

- name: "Encryption | remove the unsafe DSA public key"
  ansible.builtin.file:
    path: /etc/ssh/ssh_host_dsa_key.pub
    state: absent

- name: "Encryption | remove the unsafe DSA private key"
  ansible.builtin.file:
    path: /etc/ssh/ssh_host_dsa_key
    state: absent
