---
- name: "Install an OpenSSH server"
  ansible.builtin.include_tasks: "install.yml"

- name: "Configure SSH algorithms"
  ansible.builtin.include_tasks: "algorithms.yml"

- name: "Configure authentication methods"
  ansible.builtin.include_tasks: "authentication.yml"

- name: "Configure SSH encryption keys"
  ansible.builtin.include_tasks: "encryption.yml"

- name: "Log at VERBOSE level"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LogLevel'
    line: 'LogLevel VERBOSE'
    validate: sshd -f %s -t

- name: "Restart the SSHD service"
  changed_when: false
  ansible.builtin.service:
    name: sshd
    state: restarted
