---
  name: ansible-lint
  
  on:
    pull_request:
      branches: [ "master" ]
    push:
      branches: [ "master" ]
  
  jobs:
  
    ansible-lint:
      runs-on: ubuntu-latest
      timeout-minutes: 10
  
      steps:
        - uses: actions/checkout@v4
  
        - uses: mamba-org/setup-micromamba@d17c2171caa36ec145ac7e4658406a66d9af236d
          with:
            micromamba-version: '2.0.5-0'
            environment-file: environment.ci.yml
            init-shell: bash
            post-cleanup: 'all'
  
        - name: Check meta files with YAMLLint
          run: >
            yamllint
            environment.yml
            environment.ci.yml
          shell: micromamba-shell {0}
